# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline for the shared hosting infrastructure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main 
      - development 
  pull_request:
    branches:
      - main 
      - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  web-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🚚 Get the latest code version on the main branch
        uses: actions/checkout@v3
        
      - name: '🚀 Production deployment : Files synchronization ...' 
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          # ftp server
          server: ${{ secrets.FTP_HOST }}
          # ftp username 
          username: ${{ secrets.FTP_USERNAME }}
          # ftp password
          password: ${{ secrets.FTP_PASSWORD }}
          # server dst dir. Let it to the defualt value : ./ 
          # Who is the user default directory
      - name: '🕹️ Dev deployment : Files synchronization ...'
        if: ${{ github.ref == 'refs/heads/development' }}
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with: 
          server: ${{ secrets.DEV_FTP_SERVER }}
          username: ${{ secrets.DEV_FTP_USER }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
